# Generated by Django 3.2.13 on 2023-02-05 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('description', models.TextField(max_length=250, verbose_name='description')),
                ('number', models.IntegerField(verbose_name='number')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='number',
            field=models.IntegerField(default=1, verbose_name='number'),
        ),
        migrations.AlterField(
            model_name='article',
            name='description',
            field=models.TextField(max_length=250, verbose_name='description'),
        ),
    ]
