# Generated by Django 3.2.13 on 2023-02-05 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20230205_0024'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(null=True, upload_to='image/'),
        ),
        migrations.AddField(
            model_name='release',
            name='image',
            field=models.ImageField(null=True, upload_to='image/'),
        ),
        migrations.AddField(
            model_name='release',
            name='text',
            field=models.TextField(default='текст', verbose_name='text'),
        ),
    ]
